AcmeCorporation/AcmeCorporationWebsite/Models/ErrorViewModel.cs
namespace AcmeCorporationWebsite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AcmeCorporation/AcmeCorporationWebsite/Controllers/HomeController.cs
using AcmeCorporationLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;



namespace AcmeCorporationWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AcmeCorporation/AcmeCorporationWebsite/Controllers/SubmissionController.cs
using AcmeCorporationLibrary.Business;
using AcmeCorporationLibrary.Data;
using AcmeCorporationLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AcmeCorporationWebsite.Controllers
{
    public class SubmissionController : Controller
    {
        // Inject Database and DrawManager
        private readonly IApplicationDbContext _db;
        private readonly IDrawManager _drawManager;

        public SubmissionController(IApplicationDbContext db, IDrawManager drawManager)
        {
            _db = db;
            _drawManager = drawManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        // Get
        public IActionResult SubmitForm()
        {
            return View();
        }
        // Post
        [HttpPost]
        [ValidateAntiForgeryToken] // Prevent cross-site request forgery
        public IActionResult SubmitForm(SubmissionModel obj)
        {
            // Serverside validation
            if (string.IsNullOrEmpty(obj.FirstName))
            {
                ModelState.AddModelError("FirstName", "First name is required");
            }
            if (string.IsNullOrEmpty(obj.LastName))
            {
                ModelState.AddModelError("LastName", "Last name is required");
            }
            if (string.IsNullOrEmpty(obj.Email))
            {
                ModelState.AddModelError("Email", "Email address is required");
            }
            if (!string.IsNullOrEmpty(obj.IsOver18) && obj.IsOver18.ToLower() == "true")
            {
                obj.IsOver18 = "true";
            }
            else
            {
                ModelState.AddModelError("IsOver18", "You must be at least 18 years old.");
            }

            // Server validation for product serial number via IDrawManager injection

            if (!_drawManager.CheckAndUpdateSerialNumber(obj.ProductSerialNumber))
            {
                ModelState.AddModelError("ProductSerialNumber", "The Product serial number is invalid");
            }
            if (ModelState.IsValid)
            {
                // Save to database via IApplicationDbContext injection
                _db.Submission.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Form was submitted successfully";
                return RedirectToAction("Index","Home");
            }
            return View(obj);
        }
        // AJAX get submissions
        // List submissions in pagination of 10
        [HttpGet]
        public async Task<IActionResult> GetSubmissions(int page = 1, int pageSize = 10)
        {
            var query = _db.Submission.AsQueryable();
            var totalCount = await query.CountAsync();

            var submissions = await query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            return Json(new { Submissions = submissions, TotalCount = totalCount });
        }

    }
}

AcmeCorporation/AcmeCorporationWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1></h1>
    <p></p>
    

    <div class="card mb-3">
        <h3 class="card-header alert alert-dismissible alert-info">Enter The Draw Competition!</h3>
        <div class="card-body">
            <h4 class="card-title">Chance of winning a trip to the Bahamas!</h4>
        </div>
        <div class="image-container">
        <img src="~/Images/jakob-owens-h8T1Wa4u7oU-unsplash.jpg" alt="A stunning image of a pig swimming in the ocean, representing the draw competition for a trip to the Bahamas" style="width:100%; height:auto;">
        </div>
        <p style="text-align: center; font-style: italic; font-size: 12px;">Photo by <a href="@Html.Raw("https://unsplash.com/@jakobowens1?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash")">Jakob Owens</a> on <a href="https://unsplash.com/photos/pig-walking-on-body-of-water-during-day-h8T1Wa4u7oU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></p>
        <div class="card-body">
            <p class="card-text">To enter the draw for a chance to win a free trip to the Bahamas, simply fill out the form and submit it by the deadline.</p>
            <p class="card-text">You have to a valid serial number from purchasing one of Acme Corporation’s products and you must be at least 18 years old.</p>
        </div>
        <div class="d-grid gap-2 mb-1">
            <a asp-controller="Submission" asp-action="SubmitForm" class="btn btn-lg btn-warning" role="button">Enter the draw</a>
        </div>
        <div class="card-footer text-muted">
            Deadline: 18. November 2023
        </div>
    </div>

</div>

<style>
    .image-container {
        width: 100%;
        height: 400px; /* Define your preferred height */
        position: relative;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .image-container img {
        width: auto;
        height: 100%;
        object-fit: cover;
    }

    body {
        background-image: url('/Images/forest-simon-xa-fv2RQCPY-unsplash.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>

AcmeCorporation/AcmeCorporationWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AcmeCorporationWebsite</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AcmeCorporationWebsite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AcmeCorporationWebsite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Submission" asp-action="Index">Submissions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Submission" asp-action="SubmitForm">Enter the draw</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2023 - AcmeCorporationWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AcmeCorporation/AcmeCorporationWebsite/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
    
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

AcmeCorporation/AcmeCorporationWebsite/Views/Submission/Index.cshtml
@{
    var getUrl = Url.Action("GetSubmissions", "Submission");
}
<script>
    var submissionUrl = '@getUrl';
</script>



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Submission List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Submission" asp-action="SubmitForm" class="btn btn-success">
                <i class="bi bi-plus-circle"></i> &nbsp; Submit a new form
            </a>
        </div>
    </div>

    <div id="submission-list">
        <table class="table table-borered table-striped" style="width:100%">
            <thead>
                <tr class="table-primary">
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Product Serial Number
                    </th>
                    <th>
                        Created date
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div>
    <ul class="pagination" id="pagination">
    </ul>
</div>

<script src="~/js/submission.js"></script>


<style>
    body {
        background-image: url(~/Images/jakob-owens-h8T1Wa4u7oU-unsplash.jpg);
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        opacity: 0.9;
    }
</style>

AcmeCorporation/AcmeCorporationWebsite/Views/Submission/SubmitForm.cshtml
@model SubmissionModel


<style>
    body {
        background-image: url('/Images/forest-simon-xa-fv2RQCPY-unsplash.jpg'); 
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        opacity: 0.9;
    }
</style>


<div class ="card-header alert alert-dismissible  alert-primary mt-2">
    <h1>Welcome to the draw competition for Bahamas!</h1>

</div>
<div class="border p-3 bg-body bg-warning rounded-1">
<p>
    To enter the draw for a chance to win a free trip to the Bahamas, simply fill out the form and submit it by the deadline.<br />
    You have to a valid serial number from purchasing one of Acme Corporation’s products and you must be at least 18 years old.<br />
    A valid serial number can be used twice.
</p>
</div>
<form method="post">
    <div class="border p-3 mt-4 bg-body bg-primary rounded-1">
        <div class="row pb-2">
            <h2 class="text-primary">Submit form</h2>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ProductSerialNumber"></label>
            <input asp-for="ProductSerialNumber" class="form-control" />
        </div>
        <div class="form-check">
            <input asp-for="IsOver18" class="form-check-input" data-val="true" data-val-required="You must be at least 18 years old." type="checkbox" id="IsOver18" name="IsOver18" />
            <label asp-for="IsOver18" class="form-check-label">I agree to the terms and conditions and confirm that I am over 18 years old.</label>
        </div>
        <button type="submit" class="btn btn-success" style="width:150px">Submit</button>
        <a asp-controller="Submission" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
 
</form>

<p>Photo by <a href="@Html.Raw("https://unsplash.com/@forest_ms?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash")">Forest Simon</a> on <a href="https://unsplash.com/photos/brown-pig-in-body-of-water-xa-fv2RQCPY?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></p>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}